### PR TITLE
Execute without parameters & trns

### PR DESCRIPTION
**Pull request by bre7**

### CODE REVIEW

**Comment by davidask** [comment]
Some of these changes must first be implemented in Zewo/SQL, as that repository should reflect basic conformance of all SQL implementations. Things to consider:
- `execute` already accepts no parameters via protocol extension in `Zewo/SQL`.
- Monitoring existing transactions and throwing errors is not the job of an abstraction of `libpq` i think. If libpq doesn't allow multiple transactions, it will throw an error for us.
- `getLastErrorMessage()` is rather non-Swift in its expression. A computed property named `mostRecentErrorMessage` would be better. Minor issue, but still.

**Comment by bre7** [comment]
> execute already accepts no parameters via protocol extension in Zewo/SQL.

True, it just seemed "better" to use PQExec instead of PQexecParams.

> If libpq doesn't allow multiple transactions, it will throw an error for us.

You have to create a new session per transaction, otherwise it can't be done. I just wanted to avoid generic errors.
If one tries to do BEGIN....BEGIN, only a warning is sent: _WARNING:  there is already a transaction in progress_. So I guess the BEGIN is just ignored. Isn't it better to generate an exception ?

> getLastErrorMessage() is rather non-Swift in its expression. A computed property named mostRecentErrorMessage would be better. Minor issue, but still.

:+1:

**Comment by davidask** [comment]
Good thinking using `PQExec` when there are no parameters.
I'm not a stranger to abstracting e.g. error messages like you did to promote better usage of our API's, but if we do, i want us to take a broader perspective, starting with generic SQL.

If you review https://github.com/Zewo/SQL/blob/master/Sources/Connection.swift you'll find that there are already `begin()` `commit()` and `rollback()` methods. If we want to implement safeguards for preventing nested or double transactions, we should consider doing it via protocol extensions from the SQL library. And before we do, we need to make sure that the behaviour we're implementing makes sense for MySQL, PostgreSQL, SQLite etc.

I know this isn't quite clear at the moment, i'm sorry.

**Comment by davidask** [comment]
Same goes for `mostRecentErrorMessage`. Maybe this can be a required property in `SQL/Connection.swift`, depending on whether other SQL libs work that way. I think at least MySQL does.

**Comment by bre7** [comment]
I totally missed `commit()`, `rollback()` and `begin()` from Zewo/SQL :sweat: 

> Same goes for mostRecentErrorMessage. Maybe this can be a required property in SQL/Connection.swift, depending on whether other SQL libs work that way. I think at least MySQL does.

It does work the same in MySQL ([mysql-error](http://dev.mysql.com/doc/refman/5.7/en/mysql-error.html)) and SQLite ([sqlite3_errcode and sqlite3_errmsg](https://www.sqlite.org/c3ref/errcode.html)) ~~, but not in SQLite (result code returned by every op)~~

**Comment by davidask** [comment]
I'd say that warrants a SQL implementation rather than PostgreSQL specific :)

**Pull request closed without merging**
